name:                 vty-crossplatform
version:              0.4.0.0
visibility:           public
id:                   vty-crossplatform-0.4.0.0-inplace
key:                  vty-crossplatform-0.4.0.0-inplace
license:              LicenseRef-BSD-3
copyright:            (c) 2023 Jonathan Daugherty
maintainer:           cygnus@foobox.com
author:               Jonathan Daugherty
synopsis:             Cross-platform support for Vty
description:
    This package provides a generic interface for multiple
    Vty platforms in one package so you don't have to
    conditionally depend on them in your cabal file.

category:             Graphics
abi:                  inplace
exposed:              True
exposed-modules:
    Graphics.Vty.CrossPlatform Graphics.Vty.CrossPlatform.Testing

import-dirs:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-crossplatform-0.4.0.0/build

library-dirs:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-crossplatform-0.4.0.0/build

dynamic-library-dirs:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-crossplatform-0.4.0.0/build

data-dir:
    /home/pritin/Desktop/Haskell-Games/snake/vty-crossplatform-0.4.0.0

hs-libraries:         HSvty-crossplatform-0.4.0.0-inplace
depends:
    base-4.13.0.0
    vty-6.4-846d068c1960deb7ddb223792c77d9bd4d667ba3a5d479ea0da1a63a708ba96a
    vty-unix-0.2.0.0-inplace

haddock-interfaces:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-crossplatform-0.4.0.0/doc/html/vty-crossplatform/vty-crossplatform.haddock

haddock-html:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-crossplatform-0.4.0.0/doc/html/vty-crossplatform
