name:                 vty-unix
version:              0.2.0.0
visibility:           public
id:                   vty-unix-0.2.0.0-inplace
key:                  vty-unix-0.2.0.0-inplace
license:              LicenseRef-BSD-3
copyright:            (c) 2023 Jonathan Daugherty
maintainer:           cygnus@foobox.com
author:               Jonathan Daugherty
synopsis:             Unix backend for Vty
description:          This package provides Unix terminal support for Vty.
category:             User Interfaces
abi:                  inplace
exposed:              True
exposed-modules:
    Data.Terminfo.Eval Data.Terminfo.Parse Graphics.Vty.Platform.Unix
    Graphics.Vty.Platform.Unix.Input
    Graphics.Vty.Platform.Unix.Input.Classify
    Graphics.Vty.Platform.Unix.Input.Classify.Parse
    Graphics.Vty.Platform.Unix.Input.Classify.Types
    Graphics.Vty.Platform.Unix.Input.Focus
    Graphics.Vty.Platform.Unix.Input.Loop
    Graphics.Vty.Platform.Unix.Input.Mouse
    Graphics.Vty.Platform.Unix.Input.Paste
    Graphics.Vty.Platform.Unix.Input.Terminfo
    Graphics.Vty.Platform.Unix.Input.Terminfo.ANSIVT
    Graphics.Vty.Platform.Unix.Output
    Graphics.Vty.Platform.Unix.Output.Color
    Graphics.Vty.Platform.Unix.Output.TerminfoBased
    Graphics.Vty.Platform.Unix.Output.XTermColor
    Graphics.Vty.Platform.Unix.Settings

import-dirs:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-unix-0.2.0.0/build

library-dirs:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-unix-0.2.0.0/build

dynamic-library-dirs:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-unix-0.2.0.0/build

data-dir:             /home/pritin/Desktop/Haskell-Games/snake/vty-unix-0.2.0.0
hs-libraries:         HSvty-unix-0.2.0.0-inplace
includes:             cbits/gwinsz.h
depends:
    base-4.13.0.0
    blaze-builder-0.4.3-73669b0532aaef8eda80df149c3dd27cc8e70a75d474e46fb56b5bac15539537
    bytestring-0.10.10.1 containers-0.6.2.1 deepseq-1.4.4.0
    microlens-0.4.14.0-84c228f9c6c8a2929ae4b16b194b4106c51d668f966da3d01c052bd02f670ccd
    microlens-mtl-0.2.1.0-fabc7ba6958fb714d25d9cb46eb9182d7691838cacb0f3388fa653ca95b01e37
    microlens-th-0.4.3.17-ca6311d5fdc2a415cd93694f455463ed1a96f9eea8165aedbea852d1fdc298c4
    mtl-2.2.2 parsec-3.1.14.0 stm-2.5.0.0 terminfo-0.4.1.4
    transformers-0.5.6.2 unix-2.7.2.2
    utf8-string-1.0.2-355ee9069947f4ad2d496d2bb0b1a7b4d8ea8194220f3509625e69f2c825e575
    vector-0.13.2.0-b7190563c8a988488fb01bdad303bd67aeefe41873e33cf8aeddcc5c83f81c40
    vty-6.4-846d068c1960deb7ddb223792c77d9bd4d667ba3a5d479ea0da1a63a708ba96a

haddock-interfaces:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-unix-0.2.0.0/doc/html/vty-unix/vty-unix.haddock

haddock-html:
    /home/pritin/Desktop/Haskell-Games/snake/dist-newstyle/build/x86_64-linux/ghc-8.8.4/vty-unix-0.2.0.0/doc/html/vty-unix
